import type { Knex } from "knex";

export async function seed(knex: Knex): Promise<void> {
	await knex("source").insert([
		{
			id: 1,
			name: "Livelo",
			url: "https://www.livelo.com.br/ganhe-pontos-compre-e-pontue",
		},
	]).onConflict("id").ignore();

	await knex("partner").insert([
		{ id: 1, name: "ABC da Construcao" },
		{ id: 2, name: "Abelha Rainha" },
		{ id: 3, name: "Aguativa Resort" },
		{ id: 4, name: "AliExpress" },
		{ id: 5, name: "Allianz Travel" },
		{ id: 6, name: "Allugator" },
		{ id: 7, name: "Amazon" },
		{ id: 8, name: "AMOBELEZA" },
		{ id: 9, name: "Angeloni" },
		{ id: 10, name: "Apoio Entrega" },
		{ id: 11, name: "Asics" },
		{ id: 12, name: "Assist Card" },
		{ id: 13, name: "Atalaia Noronha" },
		{ id: 14, name: "Avis" },
		{ id: 15, name: "Avon" },
		{ id: 16, name: "Azul Viagens" },
		{ id: 17, name: "Bagaggio" },
		{ id: 18, name: "Baianão" },
		{ id: 19, name: "Basicamente" },
		{ id: 20, name: "Basico.com" },
		{ id: 21, name: "Beach Park Hotéis" },
		{ id: 22, name: "Beach Park Ingressos" },
		{ id: 23, name: "Beep" },
		{ id: 24, name: "Beleza na Web" },
		{ id: 25, name: "Beleza na Web PRO" },
		{ id: 26, name: "BeON" },
		{ id: 27, name: "Beto Carrero World" },
		{ id: 28, name: "Beyoung" },
		{ id: 29, name: "Bibi" },
		{ id: 30, name: "BoBo" },
		{ id: 31, name: "Bobstore" },
		{ id: 32, name: "Bombay Herbs & Spices" },
		{ id: 33, name: "Bonjour Lingerie" },
		{ id: 34, name: "Booking.com" },
		{ id: 35, name: "Bradesco Capitalização" },
		{ id: 36, name: "Buddha Spa" },
		{ id: 37, name: "Budget" },
		{ id: 38, name: "Buser" },
		{ id: 39, name: "Buzios Beach Resort" },
		{ id: 40, name: "C2 Tours" },
		{ id: 41, name: "Cabana Magazine" },
		{ id: 42, name: "Cadence" },
		{ id: 43, name: "Café Utam" },
		{ id: 44, name: "Café Orfeu" },
		{ id: 45, name: "Camicado" },
		{ id: 46, name: "CARE" },
		{ id: 47, name: "Carrefour Mercado" },
		{ id: 48, name: "Carrefour Shopping" },
		{ id: 49, name: "Casa MinD" },
		{ id: 50, name: "Casas Bahia" },
		{ id: 51, name: "C&A" },
		{ id: 52, name: "CervejaBox" },
		{ id: 53, name: "Cestas Michelli" },
		{ id: 54, name: "Chico Rei" },
		{ id: 55, name: "Ciclic" },
		{ id: 56, name: "Ciclic Bike" },
		{ id: 57, name: "Ciclic Seguro Celular" },
		{ id: 58, name: "ClickBus" },
		{ id: 59, name: "Coffee ++" },
		{ id: 60, name: "Coliseu" },
		{ id: 61, name: "Compra Certa" },
		{ id: 62, name: "Consórcio Magalu" },
		{ id: 63, name: "Creditas" },
		{ id: 64, name: "Crocs" },
		{ id: 65, name: "Cruzeiros Agaxtur" },
		{ id: 66, name: "Câmbio Online" },
		{ id: 67, name: "Dafiti" },
		{ id: 68, name: "Dako" },
		{ id: 69, name: "Darkness" },
		{ id: 70, name: "Decathlon" },
		{ id: 71, name: "Decolar" },
		{ id: 72, name: "Democrata" },
		{ id: 73, name: "Divvino" },
		{ id: 74, name: "DPaschoal" },
		{ id: 75, name: "Dream Fitness" },
		{ id: 76, name: "Drogaria São Paulo" },
		{ id: 77, name: "Drogarias Pacheco" },
		{ id: 78, name: "Dudalina" },
		{ id: 79, name: "Dzarm" },
		{ id: 80, name: "Easy Live" },
		{ id: 81, name: "EDP" },
		{ id: 82, name: "Ellus" },
		{ id: 83, name: "Estoque" },
		{ id: 84, name: "Eudora" },
		{ id: 85, name: "Euro" },
		{ id: 86, name: "Extra" },
		{ id: 87, name: "Faber-Castell" },
		{ id: 88, name: "Farmácias App" },
		{ id: 89, name: "Fast Shop" },
		{ id: 90, name: "Fila" },
		{ id: 91, name: "Flormel" },
		{ id: 92, name: "Foco" },
		{ id: 93, name: "Forever Liss" },
		{ id: 94, name: "Frigelar " },
		{ id: 95, name: "Fóssil" },
		{ id: 96, name: "Gazin" },
		{ id: 97, name: "Giuliana Flores" },
		{ id: 98, name: "Gocase" },
		{ id: 99, name: "Granado" },
		{ id: 100, name: "Dreams" },
		{ id: 101, name: "Guanabara" },
		{ id: 102, name: "Guess " },
		{ id: 103, name: "Guldi" },
		{ id: 104, name: "Havaianas" },
		{ id: 105, name: "Hering" },
		{ id: 106, name: "HERO SEGUROS" },
		{ id: 107, name: "Hertz Internacional" },
		{ id: 108, name: "Highstil" },
		{ id: 109, name: "Home Angels" },
		{ id: 110, name: "Hope" },
		{ id: 111, name: "Hope Resort" },
		{ id: 112, name: "Hopper" },
		{ id: 113, name: "Horas Mágicas" },
		{ id: 114, name: "Hot Beach" },
		{ id: 115, name: "Hotéis de Luxo Brasil" },
		{ id: 116, name: "Hotéis Deville" },
		{ id: 117, name: "Hoteis.com" },
		{ id: 118, name: "Hotel Gran Marquise" },
		{ id: 119, name: "Hotel Nacional" },
		{ id: 120, name: "Imaginarium" },
		{ id: 121, name: "Império" },
		{ id: 122, name: "Individual" },
		{ id: 123, name: "Infinix" },
		{ id: 124, name: "Insider Store" },
		{ id: 125, name: "IntegralMedica" },
		{ id: 126, name: "JBL" },
		{ id: 127, name: "John John" },
		{ id: 128, name: "Julio Okubo" },
		{ id: 129, name: "Kaligo" },
		{ id: 130, name: "Key Design" },
		{ id: 131, name: "Klabin ForYou" },
		{ id: 132, name: "LE LIS" },
		{ id: 133, name: "LEGO" },
		{ id: 134, name: "Liga Vitoria - Seguro de Viagem" },
		{ id: 135, name: "Liga Vitoria Seguro Auto" },
		{ id: 136, name: "Liga Vitoria Seguro de Vida" },
		{ id: 137, name: "Liga Vitoria Seguro Moto" },
		{ id: 138, name: "Liga Vitoria Seguro Residencial" },
		{ id: 139, name: "Liga Vitoria Seguro Residencial" },
		{ id: 140, name: "Liga Vitoria Seguro Viagem" },
		{ id: 141, name: "Liga Vitoria Seguros" },
		{ id: 142, name: "LIVE!" },
		{ id: 143, name: "Liz" },
		{ id: 144, name: "Localiza" },
		{ id: 145, name: "Localiza Meoo" },
		{ id: 146, name: "Loccitane" },
		{ id: 147, name: "Loccitane au Bresil" },
		{ id: 148, name: "Lolita" },
		{ id: 149, name: "Lord Perfumaria" },
		{ id: 150, name: "Loungerie" },
		{ id: 151, name: "Luck Receptivo (João Pessoa)" },
		{ id: 152, name: "Luck Receptivo (Salvador)" },
		{ id: 153, name: "Luck Receptivo (Recife)" },
		{ id: 154, name: "Luck Receptivo (Maceió)" },
		{ id: 155, name: "Luck Receptivo (Natal)" },
		{ id: 156, name: "Luxury Loyalty" },
		{ id: 157, name: "Madesa" },
		{ id: 158, name: "Magazine Luiza" },
		{ id: 159, name: "Malwee" },
		{ id: 160, name: "MAPFRE Seguro Auto" },
		{ id: 161, name: "MaxRacer" },
		{ id: 162, name: "Meia Sola" },
		{ id: 163, name: "MeuCopo" },
		{ id: 164, name: "Mevo Farma" },
		{ id: 165, name: "Midea Store" },
		{ id: 166, name: "Minimal Club" },
		{ id: 167, name: "Mistral" },
		{ id: 168, name: "Mizuno" },
		{ id: 169, name: "Mobills" },
		{ id: 170, name: "Mobly" },
		{ id: 171, name: "Mondaine" },
		{ id: 172, name: "Monica Sanches" },
		{ id: 173, name: "Monis" },
		{ id: 174, name: "Monis Pro" },
		{ id: 175, name: "Monte Carlo" },
		{ id: 176, name: "Morana" },
		{ id: 177, name: "Movida" },
		{ id: 178, name: "Mycon Consórcio Digital" },
		{ id: 179, name: "Nars" },
		{ id: 180, name: "Natura" },
		{ id: 181, name: "Netshoes" },
		{ id: 182, name: "New Balance" },
		{ id: 183, name: "Next Seguro Viagem" },
		{ id: 184, name: "Nike" },
		{ id: 185, name: "Nova Era" },
		{ id: 186, name: "Nutrify" },
		{ id: 187, name: "Nutty Bavarian" },
		{ id: 188, name: "O Boticario" },
		{ id: 189, name: "Oceane" },
		{ id: 190, name: "Oficina Reserva" },
		{ id: 191, name: "Olympikus" },
		{ id: 192, name: "Ondas Praia Resort" },
		{ id: 193, name: "Osklen" },
		{ id: 194, name: "Oster" },
		{ id: 195, name: "Oxford" },
		{ id: 196, name: "Pado" },
		{ id: 197, name: "Panvel" },
		{ id: 198, name: "Pede Pronto" },
		{ id: 199, name: "Penalty" },
		{ id: 200, name: "PerfectDraft (Ambev)" },
		{ id: 201, name: "Pet Paluche" },
		{ id: 202, name: "Pet Paluche Box" },
		{ id: 203, name: "Petlove" },
		{ id: 204, name: "Petlove Saúde" },
		{ id: 205, name: "Piatan Natural" },
		{ id: 206, name: "Pipooh" },
		{ id: 207, name: "Pontofrio" },
		{ id: 208, name: "Portal das Malas" },
		{ id: 209, name: "Portallar" },
		{ id: 210, name: "Porto Faz" },
		{ id: 211, name: "Posthaus" },
		{ id: 212, name: "Prive Hotéis e Parques" },
		{ id: 213, name: "Puket" },
		{ id: 214, name: "Qcompra" },
		{ id: 215, name: "Quem Disse, Berenice?" },
		{ id: 216, name: "Quero Passagem" },
		{ id: 217, name: "Quero-Quero" },
		{ id: 218, name: "Quintess" },
		{ id: 219, name: "RDC Viagens" },
		{ id: 220, name: "Re Petit" },
		{ id: 221, name: "Renner" },
		{ id: 222, name: "Rentalcars" },
		{ id: 223, name: "Rentcars" },
		{ id: 224, name: "Reserva" },
		{ id: 225, name: "Reservecar" },
		{ id: 226, name: "Riachuelo" },
		{ id: 227, name: "Richards" },
		{ id: 228, name: "ropo" },
		{ id: 229, name: "Saint Paul" },
		{ id: 230, name: "Salinas" },
		{ id: 231, name: "Sam's Club Assinatura" },
		{ id: 232, name: "Sam's Club" },
		{ id: 233, name: "Samsonite " },
		{ id: 234, name: "Sebastian Coffee" },
		{ id: 235, name: "Seculus" },
		{ id: 236, name: "Seguro Viagem Bradesco" },
		{ id: 237, name: "Sephora" },
		{ id: 238, name: "Seus Ingressos" },
		{ id: 239, name: "Shiseido" },
		{ id: 240, name: "Shoestock" },
		{ id: 241, name: "Simple Organic" },
		{ id: 242, name: "Simples Reserva" },
		{ id: 243, name: "Sixt" },
		{ id: 244, name: "Sottile" },
		{ id: 245, name: "Speedo" },
		{ id: 246, name: "Spicy" },
		{ id: 247, name: "Studio Z" },
		{ id: 248, name: "Summerville" },
		{ id: 249, name: "Supermercado Justo" },
		{ id: 250, name: "Supernosso" },
		{ id: 251, name: "Tailors Mind " },
		{ id: 252, name: "Technos" },
		{ id: 253, name: "The body shop" },
		{ id: 254, name: "Thule" },
		{ id: 255, name: "Tia Sônia" },
		{ id: 256, name: "TIM" },
		{ id: 257, name: "Tokio Marine" },
		{ id: 258, name: "Top Móveis" },
		{ id: 259, name: "Travel 365" },
		{ id: 260, name: "Travelex" },
		{ id: 261, name: "TripChip" },
		{ id: 262, name: "Trocafy" },
		{ id: 263, name: "Umbro" },
		{ id: 264, name: "Under Armour" },
		{ id: 265, name: "Unidas" },
		{ id: 266, name: "Universal Assistance Seguros" },
		{ id: 267, name: "Utilplast" },
		{ id: 268, name: "Viajar" },
		{ id: 269, name: "Viação Garcia" },
		{ id: 270, name: "Vivara" },
		{ id: 271, name: "VR Collezioni" },
		{ id: 272, name: "Vá de Táxi" },
		{ id: 273, name: "Wet n Wild" },
		{ id: 274, name: "Windsor Hotéis" },
		{ id: 275, name: "Wise UP" },
		{ id: 276, name: "Yvy" },
		{ id: 277, name: "Zattini" },
		{ id: 278, name: "Zissou" },
		{ id: 279, name: "Época cosmésticos" },
		{ id: 280, name: "ADCOS" },
		{ id: 281, name: "Bulbe Energia" },
		{ id: 282, name: "Caffeine Army" },
		{ id: 283, name: "Centauro" },
		{ id: 284, name: "Ciclic Seguro Viagem" },
		{ id: 285, name: "Claro" },
		{ id: 286, name: "D'Or Mais Saúde" },
		{ id: 287, name: "Dr Jones" },
		{ id: 288, name: "Hering Outlet" },
		{ id: 289, name: "Lacoste" },
		{ id: 290, name: "Aramis" },
		{ id: 291, name: "Max Titanium" },
		{ id: 292, name: "MedSenior" },
		{ id: 293, name: "OUi Paris" },
		{ id: 294, name: "Probiotica" },
		{ id: 295, name: "Seguro Residencial MAPFRE" },
		{ id: 296, name: "Shopee" },
		{ id: 297, name: "Vult" },
	]).onConflict("id").merge();

	await knex("partner_source").insert([
		{
			partner_id: 1,
			source_id: 1,
			reference: JSON.stringify({ title: "ABC da Construcao" }),
		},
		{
			partner_id: 2,
			source_id: 1,
			reference: JSON.stringify({ title: "Abelha Rainha" }),
		},
		{
			partner_id: 3,
			source_id: 1,
			reference: JSON.stringify({ title: "Aguativa Resort" }),
		},
		{
			partner_id: 4,
			source_id: 1,
			reference: JSON.stringify({ title: "Aliexpress" }),
		},
		{
			partner_id: 5,
			source_id: 1,
			reference: JSON.stringify({ title: "Allianz" }),
		},
		{
			partner_id: 6,
			source_id: 1,
			reference: JSON.stringify({ title: "Allugator" }),
		},
		{
			partner_id: 7,
			source_id: 1,
			reference: JSON.stringify({ title: "Amazon" }),
		},
		{
			partner_id: 8,
			source_id: 1,
			reference: JSON.stringify({ title: "AMOBELEZA" }),
		},
		{
			partner_id: 9,
			source_id: 1,
			reference: JSON.stringify({ title: "Angeloni" }),
		},
		{
			partner_id: 10,
			source_id: 1,
			reference: JSON.stringify({ title: "Apoio Entregas" }),
		},
		{
			partner_id: 11,
			source_id: 1,
			reference: JSON.stringify({ title: "Asics" }),
		},
		{
			partner_id: 12,
			source_id: 1,
			reference: JSON.stringify({ title: "Assist Card Seguros" }),
		},
		{
			partner_id: 13,
			source_id: 1,
			reference: JSON.stringify({ title: "Atalaia Noronha" }),
		},
		{
			partner_id: 14,
			source_id: 1,
			reference: JSON.stringify({ title: "avis" }),
		},
		{
			partner_id: 15,
			source_id: 1,
			reference: JSON.stringify({ title: "Avon" }),
		},
		{
			partner_id: 16,
			source_id: 1,
			reference: JSON.stringify({ title: "Azul Viagens" }),
		},
		{
			partner_id: 17,
			source_id: 1,
			reference: JSON.stringify({ title: "Bagaggio" }),
		},
		{
			partner_id: 18,
			source_id: 1,
			reference: JSON.stringify({ title: "Baianao" }),
		},
		{
			partner_id: 19,
			source_id: 1,
			reference: JSON.stringify({ title: "Basicamente" }),
		},
		{
			partner_id: 20,
			source_id: 1,
			reference: JSON.stringify({ title: "Basico.com" }),
		},
		{
			partner_id: 21,
			source_id: 1,
			reference: JSON.stringify({ title: "Beach Park Hospedagens" }),
		},
		{
			partner_id: 22,
			source_id: 1,
			reference: JSON.stringify({ title: "Beach Park Ingressos" }),
		},
		{
			partner_id: 23,
			source_id: 1,
			reference: JSON.stringify({ title: "Beep" }),
		},
		{
			partner_id: 24,
			source_id: 1,
			reference: JSON.stringify({ title: "Beleza na web" }),
		},
		{
			partner_id: 25,
			source_id: 1,
			reference: JSON.stringify({ title: "Beleza na Web PRO" }),
		},
		{
			partner_id: 26,
			source_id: 1,
			reference: JSON.stringify({ title: "BeOn" }),
		},
		{
			partner_id: 27,
			source_id: 1,
			reference: JSON.stringify({ title: "Beto Carrero World" }),
		},
		{
			partner_id: 28,
			source_id: 1,
			reference: JSON.stringify({ title: "Beyoung" }),
		},
		{
			partner_id: 29,
			source_id: 1,
			reference: JSON.stringify({ title: "Bibi" }),
		},
		{
			partner_id: 30,
			source_id: 1,
			reference: JSON.stringify({ title: "BoBo" }),
		},
		{
			partner_id: 31,
			source_id: 1,
			reference: JSON.stringify({ title: "Bobstore" }),
		},
		{
			partner_id: 32,
			source_id: 1,
			reference: JSON.stringify({ title: "Bombay Herbs & Spices" }),
		},
		{
			partner_id: 33,
			source_id: 1,
			reference: JSON.stringify({ title: "Bonjour Lingerie" }),
		},
		{
			partner_id: 34,
			source_id: 1,
			reference: JSON.stringify({ title: "Booking.com" }),
		},
		{
			partner_id: 35,
			source_id: 1,
			reference: JSON.stringify({ title: "Bradesco Capitalizacao" }),
		},
		{
			partner_id: 36,
			source_id: 1,
			reference: JSON.stringify({ title: "Buddha Spa" }),
		},
		{
			partner_id: 37,
			source_id: 1,
			reference: JSON.stringify({ title: "Budget" }),
		},
		{
			partner_id: 38,
			source_id: 1,
			reference: JSON.stringify({ title: "Buser" }),
		},
		{
			partner_id: 39,
			source_id: 1,
			reference: JSON.stringify({ title: "Buzios Beach Resort" }),
		},
		{
			partner_id: 40,
			source_id: 1,
			reference: JSON.stringify({ title: "C2 Tours" }),
		},
		{
			partner_id: 41,
			source_id: 1,
			reference: JSON.stringify({ title: "Cabana Magazine" }),
		},
		{
			partner_id: 42,
			source_id: 1,
			reference: JSON.stringify({ title: "Cadence" }),
		},
		{
			partner_id: 43,
			source_id: 1,
			reference: JSON.stringify({ title: "Cafe Utam" }),
		},
		{
			partner_id: 44,
			source_id: 1,
			reference: JSON.stringify({ title: "Cafe Orfeu" }),
		},
		{
			partner_id: 45,
			source_id: 1,
			reference: JSON.stringify({ title: "Camicado" }),
		},
		{
			partner_id: 46,
			source_id: 1,
			reference: JSON.stringify({ title: "CARE Natural Beauty" }),
		},
		{
			partner_id: 47,
			source_id: 1,
			reference: JSON.stringify({ title: "Carrefour Mercado" }),
		},
		{
			partner_id: 48,
			source_id: 1,
			reference: JSON.stringify({ title: "Carrefour Shopping" }),
		},
		{
			partner_id: 49,
			source_id: 1,
			reference: JSON.stringify({ title: "Casa MinD" }),
		},
		{
			partner_id: 50,
			source_id: 1,
			reference: JSON.stringify({ title: "Casas Bahia" }),
		},
		{
			partner_id: 51,
			source_id: 1,
			reference: JSON.stringify({ title: "CEA" }),
		},
		{
			partner_id: 52,
			source_id: 1,
			reference: JSON.stringify({ title: "Cervejabox" }),
		},
		{
			partner_id: 53,
			source_id: 1,
			reference: JSON.stringify({ title: "Cestas Michelli" }),
		},
		{
			partner_id: 54,
			source_id: 1,
			reference: JSON.stringify({ title: "Chico Rei" }),
		},
		{
			partner_id: 55,
			source_id: 1,
			reference: JSON.stringify({ title: "Ciclic" }),
		},
		{
			partner_id: 56,
			source_id: 1,
			reference: JSON.stringify({ title: "Ciclic Bike" }),
		},
		{
			partner_id: 57,
			source_id: 1,
			reference: JSON.stringify({ title: "Ciclic Seguro Celular" }),
		},
		{
			partner_id: 58,
			source_id: 1,
			reference: JSON.stringify({ title: "ClickBus" }),
		},
		{
			partner_id: 59,
			source_id: 1,
			reference: JSON.stringify({ title: "Coffee Mais" }),
		},
		{
			partner_id: 60,
			source_id: 1,
			reference: JSON.stringify({ title: "Coliseu" }),
		},
		{
			partner_id: 61,
			source_id: 1,
			reference: JSON.stringify({ title: "Compra Certa" }),
		},
		{
			partner_id: 62,
			source_id: 1,
			reference: JSON.stringify({ title: "Consorcio Magalu" }),
		},
		{
			partner_id: 63,
			source_id: 1,
			reference: JSON.stringify({ title: "Creditas" }),
		},
		{
			partner_id: 64,
			source_id: 1,
			reference: JSON.stringify({ title: "Crocs" }),
		},
		{
			partner_id: 65,
			source_id: 1,
			reference: JSON.stringify({ title: "Cruzeiros Agaxtur" }),
		},
		{
			partner_id: 66,
			source_id: 1,
			reference: JSON.stringify({ title: "Cambio Online" }),
		},
		{
			partner_id: 67,
			source_id: 1,
			reference: JSON.stringify({ title: "Dafiti" }),
		},
		{
			partner_id: 68,
			source_id: 1,
			reference: JSON.stringify({ title: "Dako" }),
		},
		{
			partner_id: 69,
			source_id: 1,
			reference: JSON.stringify({ title: "Darkness" }),
		},
		{
			partner_id: 70,
			source_id: 1,
			reference: JSON.stringify({ title: "Decathlon" }),
		},
		{
			partner_id: 71,
			source_id: 1,
			reference: JSON.stringify({ title: "Decolar" }),
		},
		{
			partner_id: 72,
			source_id: 1,
			reference: JSON.stringify({ title: "Democrata" }),
		},
		{
			partner_id: 73,
			source_id: 1,
			reference: JSON.stringify({ title: "Divvino" }),
		},
		{
			partner_id: 74,
			source_id: 1,
			reference: JSON.stringify({ title: "DPaschoal" }),
		},
		{
			partner_id: 75,
			source_id: 1,
			reference: JSON.stringify({ title: "Dream Fitness" }),
		},
		{
			partner_id: 76,
			source_id: 1,
			reference: JSON.stringify({ title: "Drogaria Sao Paulo" }),
		},
		{
			partner_id: 77,
			source_id: 1,
			reference: JSON.stringify({ title: "Drogarias Pacheco" }),
		},
		{
			partner_id: 78,
			source_id: 1,
			reference: JSON.stringify({ title: "Dudalina" }),
		},
		{
			partner_id: 79,
			source_id: 1,
			reference: JSON.stringify({ title: "Dzarm" }),
		},
		{
			partner_id: 80,
			source_id: 1,
			reference: JSON.stringify({ title: "Easy Live" }),
		},
		{
			partner_id: 81,
			source_id: 1,
			reference: JSON.stringify({ title: "EDP" }),
		},
		{
			partner_id: 82,
			source_id: 1,
			reference: JSON.stringify({ title: "Ellus" }),
		},
		{
			partner_id: 83,
			source_id: 1,
			reference: JSON.stringify({ title: "Estoque" }),
		},
		{
			partner_id: 84,
			source_id: 1,
			reference: JSON.stringify({ title: "Eudora" }),
		},
		{
			partner_id: 85,
			source_id: 1,
			reference: JSON.stringify({ title: "Euro" }),
		},
		{
			partner_id: 86,
			source_id: 1,
			reference: JSON.stringify({ title: "Extra" }),
		},
		{
			partner_id: 87,
			source_id: 1,
			reference: JSON.stringify({ title: "Faber-Castell" }),
		},
		{
			partner_id: 88,
			source_id: 1,
			reference: JSON.stringify({ title: "Farmacias App" }),
		},
		{
			partner_id: 89,
			source_id: 1,
			reference: JSON.stringify({ title: "Fast Shop" }),
		},
		{
			partner_id: 90,
			source_id: 1,
			reference: JSON.stringify({ title: "Fila" }),
		},
		{
			partner_id: 91,
			source_id: 1,
			reference: JSON.stringify({ title: "Flormel" }),
		},
		{
			partner_id: 92,
			source_id: 1,
			reference: JSON.stringify({ title: "Foco" }),
		},
		{
			partner_id: 93,
			source_id: 1,
			reference: JSON.stringify({ title: "Forever Liss" }),
		},
		{
			partner_id: 94,
			source_id: 1,
			reference: JSON.stringify({ title: "Frigelar " }),
		},
		{
			partner_id: 95,
			source_id: 1,
			reference: JSON.stringify({ title: "Fossil" }),
		},
		{
			partner_id: 96,
			source_id: 1,
			reference: JSON.stringify({ title: "Gazin" }),
		},
		{
			partner_id: 97,
			source_id: 1,
			reference: JSON.stringify({ title: "Giuliana Flores" }),
		},
		{
			partner_id: 98,
			source_id: 1,
			reference: JSON.stringify({ title: "Go case" }),
		},
		{
			partner_id: 99,
			source_id: 1,
			reference: JSON.stringify({ title: "Granado" }),
		},
		{
			partner_id: 100,
			source_id: 1,
			reference: JSON.stringify({ title: "Grupo Dreams" }),
		},
		{
			partner_id: 101,
			source_id: 1,
			reference: JSON.stringify({ title: "Guanabara" }),
		},
		{
			partner_id: 102,
			source_id: 1,
			reference: JSON.stringify({ title: "Guess " }),
		},
		{
			partner_id: 103,
			source_id: 1,
			reference: JSON.stringify({ title: "Guldi" }),
		},
		{
			partner_id: 104,
			source_id: 1,
			reference: JSON.stringify({ title: "Havaianas" }),
		},
		{
			partner_id: 105,
			source_id: 1,
			reference: JSON.stringify({ title: "Hering" }),
		},
		{
			partner_id: 106,
			source_id: 1,
			reference: JSON.stringify({ title: "HERO SEGUROS" }),
		},
		{
			partner_id: 107,
			source_id: 1,
			reference: JSON.stringify({ title: "Hertz Internacional" }),
		},
		{
			partner_id: 108,
			source_id: 1,
			reference: JSON.stringify({ title: "Highstil " }),
		},
		{
			partner_id: 109,
			source_id: 1,
			reference: JSON.stringify({ title: "Home Angels" }),
		},
		{
			partner_id: 110,
			source_id: 1,
			reference: JSON.stringify({ title: "Hope" }),
		},
		{
			partner_id: 111,
			source_id: 1,
			reference: JSON.stringify({ title: "Hope Resort" }),
		},
		{
			partner_id: 112,
			source_id: 1,
			reference: JSON.stringify({ title: "Hopper Nutrition" }),
		},
		{
			partner_id: 113,
			source_id: 1,
			reference: JSON.stringify({ title: "Horas Magicas" }),
		},
		{
			partner_id: 114,
			source_id: 1,
			reference: JSON.stringify({ title: "Hot Beach" }),
		},
		{
			partner_id: 115,
			source_id: 1,
			reference: JSON.stringify({ title: "Hoteis de Luxo Brasil" }),
		},
		{
			partner_id: 116,
			source_id: 1,
			reference: JSON.stringify({ title: "Hoteis Deville" }),
		},
		{
			partner_id: 117,
			source_id: 1,
			reference: JSON.stringify({ title: "Hoteis.com" }),
		},
		{
			partner_id: 118,
			source_id: 1,
			reference: JSON.stringify({ title: "Hotel Gran Marquise" }),
		},
		{
			partner_id: 119,
			source_id: 1,
			reference: JSON.stringify({ title: "Hotel Nacional" }),
		},
		{
			partner_id: 120,
			source_id: 1,
			reference: JSON.stringify({ title: "Imaginarium" }),
		},
		{
			partner_id: 121,
			source_id: 1,
			reference: JSON.stringify({ title: "Imperio" }),
		},
		{
			partner_id: 122,
			source_id: 1,
			reference: JSON.stringify({ title: "Individual" }),
		},
		{
			partner_id: 123,
			source_id: 1,
			reference: JSON.stringify({ title: "Infinix" }),
		},
		{
			partner_id: 124,
			source_id: 1,
			reference: JSON.stringify({ title: "Insider Store" }),
		},
		{
			partner_id: 125,
			source_id: 1,
			reference: JSON.stringify({ title: "IntegralMedica" }),
		},
		{
			partner_id: 126,
			source_id: 1,
			reference: JSON.stringify({ title: "JBL" }),
		},
		{
			partner_id: 127,
			source_id: 1,
			reference: JSON.stringify({ title: "John John" }),
		},
		{
			partner_id: 128,
			source_id: 1,
			reference: JSON.stringify({ title: "Julio Okubo" }),
		},
		{
			partner_id: 129,
			source_id: 1,
			reference: JSON.stringify({ title: "Kaligo" }),
		},
		{
			partner_id: 130,
			source_id: 1,
			reference: JSON.stringify({ title: "Key Design" }),
		},
		{
			partner_id: 131,
			source_id: 1,
			reference: JSON.stringify({ title: "Klabin ForYou" }),
		},
		{
			partner_id: 132,
			source_id: 1,
			reference: JSON.stringify({ title: "LE LIS" }),
		},
		{
			partner_id: 133,
			source_id: 1,
			reference: JSON.stringify({ title: "LEGO" }),
		},
		{
			partner_id: 134,
			source_id: 1,
			reference: JSON.stringify({ title: "Liga Vitória - Seguro de Viagem" }),
		},
		{
			partner_id: 135,
			source_id: 1,
			reference: JSON.stringify({ title: "Liga Vitória Seguro Auto" }),
		},
		{
			partner_id: 136,
			source_id: 1,
			reference: JSON.stringify({ title: "Liga Vitória Seguro de Vida" }),
		},
		{
			partner_id: 137,
			source_id: 1,
			reference: JSON.stringify({ title: "Liga Vitória Seguro Moto" }),
		},
		{
			partner_id: 138,
			source_id: 1,
			reference: JSON.stringify({ title: "Liga Vitória Seguro Residencial" }),
		},
		{
			partner_id: 139,
			source_id: 1,
			reference: JSON.stringify({ title: "Liga Vitória Seguro Residencial" }),
		},
		{
			partner_id: 140,
			source_id: 1,
			reference: JSON.stringify({ title: "Liga Vitória Seguro Viagem" }),
		},
		{
			partner_id: 141,
			source_id: 1,
			reference: JSON.stringify({ title: "Liga Vitória Seguros" }),
		},
		{
			partner_id: 142,
			source_id: 1,
			reference: JSON.stringify({ title: "LIVE!" }),
		},
		{
			partner_id: 143,
			source_id: 1,
			reference: JSON.stringify({ title: "Liz" }),
		},
		{
			partner_id: 144,
			source_id: 1,
			reference: JSON.stringify({ title: "Localiza" }),
		},
		{
			partner_id: 145,
			source_id: 1,
			reference: JSON.stringify({ title: "Localiza Meoo" }),
		},
		{
			partner_id: 146,
			source_id: 1,
			reference: JSON.stringify({ title: "Loccitane" }),
		},
		{
			partner_id: 147,
			source_id: 1,
			reference: JSON.stringify({ title: "Loccitane au Bresil" }),
		},
		{
			partner_id: 148,
			source_id: 1,
			reference: JSON.stringify({ title: "Lolita" }),
		},
		{
			partner_id: 149,
			source_id: 1,
			reference: JSON.stringify({ title: "Lord Perfumaria" }),
		},
		{
			partner_id: 150,
			source_id: 1,
			reference: JSON.stringify({ title: "Loungerie" }),
		},
		{
			partner_id: 151,
			source_id: 1,
			reference: JSON.stringify({ title: "Luck Receptivo (Joao Pessoa)" }),
		},
		{
			partner_id: 152,
			source_id: 1,
			reference: JSON.stringify({ title: "Luck Receptivo (Salvador)" }),
		},
		{
			partner_id: 153,
			source_id: 1,
			reference: JSON.stringify({ title: "Luck Receptivo - Recife" }),
		},
		{
			partner_id: 154,
			source_id: 1,
			reference: JSON.stringify({ title: "Luck Receptivo Maceio" }),
		},
		{
			partner_id: 155,
			source_id: 1,
			reference: JSON.stringify({ title: "Luck Receptivo Natal" }),
		},
		{
			partner_id: 156,
			source_id: 1,
			reference: JSON.stringify({ title: "Luxury Loyalty" }),
		},
		{
			partner_id: 157,
			source_id: 1,
			reference: JSON.stringify({ title: "Madesa" }),
		},
		{
			partner_id: 158,
			source_id: 1,
			reference: JSON.stringify({ title: "Magalu" }),
		},
		{
			partner_id: 159,
			source_id: 1,
			reference: JSON.stringify({ title: "Malwee" }),
		},
		{
			partner_id: 160,
			source_id: 1,
			reference: JSON.stringify({ title: "MAPFRE Seguro Auto" }),
		},
		{
			partner_id: 161,
			source_id: 1,
			reference: JSON.stringify({ title: "MaxRacer" }),
		},
		{
			partner_id: 162,
			source_id: 1,
			reference: JSON.stringify({ title: "Meia Sola" }),
		},
		{
			partner_id: 163,
			source_id: 1,
			reference: JSON.stringify({ title: "MeuCopo" }),
		},
		{
			partner_id: 164,
			source_id: 1,
			reference: JSON.stringify({ title: "Mevo Farma" }),
		},
		{
			partner_id: 165,
			source_id: 1,
			reference: JSON.stringify({ title: "Midea" }),
		},
		{
			partner_id: 166,
			source_id: 1,
			reference: JSON.stringify({ title: "Minimal Club" }),
		},
		{
			partner_id: 167,
			source_id: 1,
			reference: JSON.stringify({ title: "Mistral" }),
		},
		{
			partner_id: 168,
			source_id: 1,
			reference: JSON.stringify({ title: "Mizuno" }),
		},
		{
			partner_id: 169,
			source_id: 1,
			reference: JSON.stringify({ title: "Mobills" }),
		},
		{
			partner_id: 170,
			source_id: 1,
			reference: JSON.stringify({ title: "Mobly" }),
		},
		{
			partner_id: 171,
			source_id: 1,
			reference: JSON.stringify({ title: "Mondaine" }),
		},
		{
			partner_id: 172,
			source_id: 1,
			reference: JSON.stringify({ title: "Monica Sanches" }),
		},
		{
			partner_id: 173,
			source_id: 1,
			reference: JSON.stringify({ title: "Monis" }),
		},
		{
			partner_id: 174,
			source_id: 1,
			reference: JSON.stringify({ title: "Monis Pro" }),
		},
		{
			partner_id: 175,
			source_id: 1,
			reference: JSON.stringify({ title: "Monte Carlo" }),
		},
		{
			partner_id: 176,
			source_id: 1,
			reference: JSON.stringify({ title: "Morana" }),
		},
		{
			partner_id: 177,
			source_id: 1,
			reference: JSON.stringify({ title: "Movida" }),
		},
		{
			partner_id: 178,
			source_id: 1,
			reference: JSON.stringify({ title: "Mycon Consorcio Digital" }),
		},
		{
			partner_id: 179,
			source_id: 1,
			reference: JSON.stringify({ title: "Nars" }),
		},
		{
			partner_id: 180,
			source_id: 1,
			reference: JSON.stringify({ title: "Natura" }),
		},
		{
			partner_id: 181,
			source_id: 1,
			reference: JSON.stringify({ title: "Netshoes" }),
		},
		{
			partner_id: 182,
			source_id: 1,
			reference: JSON.stringify({ title: "New Balance" }),
		},
		{
			partner_id: 183,
			source_id: 1,
			reference: JSON.stringify({ title: "Next Seguro Viagem" }),
		},
		{
			partner_id: 184,
			source_id: 1,
			reference: JSON.stringify({ title: "Nike" }),
		},
		{
			partner_id: 185,
			source_id: 1,
			reference: JSON.stringify({ title: "Nova Era" }),
		},
		{
			partner_id: 186,
			source_id: 1,
			reference: JSON.stringify({ title: "Nutrify" }),
		},
		{
			partner_id: 187,
			source_id: 1,
			reference: JSON.stringify({ title: "Nutty Bavarian" }),
		},
		{
			partner_id: 188,
			source_id: 1,
			reference: JSON.stringify({ title: "O Boticario" }),
		},
		{
			partner_id: 189,
			source_id: 1,
			reference: JSON.stringify({ title: "Oceane" }),
		},
		{
			partner_id: 190,
			source_id: 1,
			reference: JSON.stringify({ title: "Oficina Reserva" }),
		},
		{
			partner_id: 191,
			source_id: 1,
			reference: JSON.stringify({ title: "Olympikus" }),
		},
		{
			partner_id: 192,
			source_id: 1,
			reference: JSON.stringify({ title: "Ondas Praia Resort" }),
		},
		{
			partner_id: 193,
			source_id: 1,
			reference: JSON.stringify({ title: "Osklen" }),
		},
		{
			partner_id: 194,
			source_id: 1,
			reference: JSON.stringify({ title: "Oster" }),
		},
		{
			partner_id: 195,
			source_id: 1,
			reference: JSON.stringify({ title: "Oxford" }),
		},
		{
			partner_id: 196,
			source_id: 1,
			reference: JSON.stringify({ title: "Pado" }),
		},
		{
			partner_id: 197,
			source_id: 1,
			reference: JSON.stringify({ title: "Panvel" }),
		},
		{
			partner_id: 198,
			source_id: 1,
			reference: JSON.stringify({ title: "Pede Pronto" }),
		},
		{
			partner_id: 199,
			source_id: 1,
			reference: JSON.stringify({ title: "Penalty " }),
		},
		{
			partner_id: 200,
			source_id: 1,
			reference: JSON.stringify({ title: "PerfectDraft (Ambev)" }),
		},
		{
			partner_id: 201,
			source_id: 1,
			reference: JSON.stringify({ title: "Pet Paluche" }),
		},
		{
			partner_id: 202,
			source_id: 1,
			reference: JSON.stringify({ title: "Pet Paluche Box" }),
		},
		{
			partner_id: 203,
			source_id: 1,
			reference: JSON.stringify({ title: "Petlove" }),
		},
		{
			partner_id: 204,
			source_id: 1,
			reference: JSON.stringify({ title: "Petlove Saude" }),
		},
		{
			partner_id: 205,
			source_id: 1,
			reference: JSON.stringify({ title: "Piatan Natural" }),
		},
		{
			partner_id: 206,
			source_id: 1,
			reference: JSON.stringify({ title: "Pipooh " }),
		},
		{
			partner_id: 207,
			source_id: 1,
			reference: JSON.stringify({ title: "Pontofrio" }),
		},
		{
			partner_id: 208,
			source_id: 1,
			reference: JSON.stringify({ title: "Portal das Malas" }),
		},
		{
			partner_id: 209,
			source_id: 1,
			reference: JSON.stringify({ title: "Portallar" }),
		},
		{
			partner_id: 210,
			source_id: 1,
			reference: JSON.stringify({ title: "Porto Faz" }),
		},
		{
			partner_id: 211,
			source_id: 1,
			reference: JSON.stringify({ title: "Posthaus" }),
		},
		{
			partner_id: 212,
			source_id: 1,
			reference: JSON.stringify({ title: "Prive Hoteis e Parques" }),
		},
		{
			partner_id: 213,
			source_id: 1,
			reference: JSON.stringify({ title: "Puket" }),
		},
		{
			partner_id: 214,
			source_id: 1,
			reference: JSON.stringify({ title: "Qcompra" }),
		},
		{
			partner_id: 215,
			source_id: 1,
			reference: JSON.stringify({ title: "Quem Disse, Berenice?" }),
		},
		{
			partner_id: 216,
			source_id: 1,
			reference: JSON.stringify({ title: "Quero Passagem" }),
		},
		{
			partner_id: 217,
			source_id: 1,
			reference: JSON.stringify({ title: "Quero-Quero" }),
		},
		{
			partner_id: 218,
			source_id: 1,
			reference: JSON.stringify({ title: "Quintess" }),
		},
		{
			partner_id: 219,
			source_id: 1,
			reference: JSON.stringify({ title: "RDC Viagens" }),
		},
		{
			partner_id: 220,
			source_id: 1,
			reference: JSON.stringify({ title: "Re Petit" }),
		},
		{
			partner_id: 221,
			source_id: 1,
			reference: JSON.stringify({ title: "Renner" }),
		},
		{
			partner_id: 222,
			source_id: 1,
			reference: JSON.stringify({ title: "Rentalcars" }),
		},
		{
			partner_id: 223,
			source_id: 1,
			reference: JSON.stringify({ title: "Rentcars" }),
		},
		{
			partner_id: 224,
			source_id: 1,
			reference: JSON.stringify({ title: "Reserva" }),
		},
		{
			partner_id: 225,
			source_id: 1,
			reference: JSON.stringify({ title: "Reservecar" }),
		},
		{
			partner_id: 226,
			source_id: 1,
			reference: JSON.stringify({ title: "Riachuelo" }),
		},
		{
			partner_id: 227,
			source_id: 1,
			reference: JSON.stringify({ title: "Richards" }),
		},
		{
			partner_id: 228,
			source_id: 1,
			reference: JSON.stringify({ title: "ropo®️" }),
		},
		{
			partner_id: 229,
			source_id: 1,
			reference: JSON.stringify({ title: "Saint Paul" }),
		},
		{
			partner_id: 230,
			source_id: 1,
			reference: JSON.stringify({ title: "Salinas" }),
		},
		{
			partner_id: 231,
			source_id: 1,
			reference: JSON.stringify({ title: "Sam's Club" }),
		},
		{
			partner_id: 232,
			source_id: 1,
			reference: JSON.stringify({ title: "Sam's Club - E-commerce" }),
		},
		{
			partner_id: 233,
			source_id: 1,
			reference: JSON.stringify({ title: "Samsonite " }),
		},
		{
			partner_id: 234,
			source_id: 1,
			reference: JSON.stringify({ title: "Sebastian Coffee" }),
		},
		{
			partner_id: 235,
			source_id: 1,
			reference: JSON.stringify({ title: "Seculus" }),
		},
		{
			partner_id: 236,
			source_id: 1,
			reference: JSON.stringify({ title: "Seguro Viagem Bradesco" }),
		},
		{
			partner_id: 237,
			source_id: 1,
			reference: JSON.stringify({ title: "Sephora" }),
		},
		{
			partner_id: 238,
			source_id: 1,
			reference: JSON.stringify({ title: "Seus Ingressos" }),
		},
		{
			partner_id: 239,
			source_id: 1,
			reference: JSON.stringify({ title: "Shiseido" }),
		},
		{
			partner_id: 240,
			source_id: 1,
			reference: JSON.stringify({ title: "Shoestock" }),
		},
		{
			partner_id: 241,
			source_id: 1,
			reference: JSON.stringify({ title: "Simple Organic" }),
		},
		{
			partner_id: 242,
			source_id: 1,
			reference: JSON.stringify({ title: "Simples Reserva" }),
		},
		{
			partner_id: 243,
			source_id: 1,
			reference: JSON.stringify({ title: "Sixt" }),
		},
		{
			partner_id: 244,
			source_id: 1,
			reference: JSON.stringify({ title: "Sottile" }),
		},
		{
			partner_id: 245,
			source_id: 1,
			reference: JSON.stringify({ title: "Speedo" }),
		},
		{
			partner_id: 246,
			source_id: 1,
			reference: JSON.stringify({ title: "Spicy" }),
		},
		{
			partner_id: 247,
			source_id: 1,
			reference: JSON.stringify({ title: "Studio Z" }),
		},
		{
			partner_id: 248,
			source_id: 1,
			reference: JSON.stringify({ title: "Summerville" }),
		},
		{
			partner_id: 249,
			source_id: 1,
			reference: JSON.stringify({ title: "Supermercado Justo" }),
		},
		{
			partner_id: 250,
			source_id: 1,
			reference: JSON.stringify({ title: "Supernosso" }),
		},
		{
			partner_id: 251,
			source_id: 1,
			reference: JSON.stringify({ title: "Tailors Mind " }),
		},
		{
			partner_id: 252,
			source_id: 1,
			reference: JSON.stringify({ title: "Technos" }),
		},
		{
			partner_id: 253,
			source_id: 1,
			reference: JSON.stringify({ title: "The body shop" }),
		},
		{
			partner_id: 254,
			source_id: 1,
			reference: JSON.stringify({ title: "Thule" }),
		},
		{
			partner_id: 255,
			source_id: 1,
			reference: JSON.stringify({ title: "Tia Sonia" }),
		},
		{
			partner_id: 256,
			source_id: 1,
			reference: JSON.stringify({ title: "TIM" }),
		},
		{
			partner_id: 257,
			source_id: 1,
			reference: JSON.stringify({ title: "Tokio Marine Seguros" }),
		},
		{
			partner_id: 258,
			source_id: 1,
			reference: JSON.stringify({ title: "Top Moveis" }),
		},
		{
			partner_id: 259,
			source_id: 1,
			reference: JSON.stringify({ title: "Travel 365" }),
		},
		{
			partner_id: 260,
			source_id: 1,
			reference: JSON.stringify({ title: "Travelex" }),
		},
		{
			partner_id: 261,
			source_id: 1,
			reference: JSON.stringify({ title: "TripChip" }),
		},
		{
			partner_id: 262,
			source_id: 1,
			reference: JSON.stringify({ title: "Trocafy" }),
		},
		{
			partner_id: 263,
			source_id: 1,
			reference: JSON.stringify({ title: "Umbro" }),
		},
		{
			partner_id: 264,
			source_id: 1,
			reference: JSON.stringify({ title: "Under Armour" }),
		},
		{
			partner_id: 265,
			source_id: 1,
			reference: JSON.stringify({ title: "Unidas" }),
		},
		{
			partner_id: 266,
			source_id: 1,
			reference: JSON.stringify({ title: "Universal Assistance Seguros" }),
		},
		{
			partner_id: 267,
			source_id: 1,
			reference: JSON.stringify({ title: "Utilplast" }),
		},
		{
			partner_id: 268,
			source_id: 1,
			reference: JSON.stringify({ title: "Viajar" }),
		},
		{
			partner_id: 269,
			source_id: 1,
			reference: JSON.stringify({ title: "Viacao Garcia" }),
		},
		{
			partner_id: 270,
			source_id: 1,
			reference: JSON.stringify({ title: "Vivara" }),
		},
		{
			partner_id: 271,
			source_id: 1,
			reference: JSON.stringify({ title: "VR Collezioni" }),
		},
		{
			partner_id: 272,
			source_id: 1,
			reference: JSON.stringify({ title: "Vá de Táxi" }),
		},
		{
			partner_id: 273,
			source_id: 1,
			reference: JSON.stringify({ title: "Wet n Wild" }),
		},
		{
			partner_id: 274,
			source_id: 1,
			reference: JSON.stringify({ title: "Hoteis Windsor" }),
		},
		{
			partner_id: 275,
			source_id: 1,
			reference: JSON.stringify({ title: "Wise UP" }),
		},
		{
			partner_id: 276,
			source_id: 1,
			reference: JSON.stringify({ title: "Yvy" }),
		},
		{
			partner_id: 277,
			source_id: 1,
			reference: JSON.stringify({ title: "Zattini" }),
		},
		{
			partner_id: 278,
			source_id: 1,
			reference: JSON.stringify({ title: "Zissou" }),
		},
		{
			partner_id: 279,
			source_id: 1,
			reference: JSON.stringify({ title: "Epoca cosmesticos" }),
		},
		{
			partner_id: 280,
			source_id: 1,
			reference: JSON.stringify({ title: "ADCOS" }),
		},
		{
			partner_id: 281,
			source_id: 1,
			reference: JSON.stringify({ title: "Bulbe Energia" }),
		},
		{
			partner_id: 282,
			source_id: 1,
			reference: JSON.stringify({ title: "Caffeine Army" }),
		},
		{
			partner_id: 283,
			source_id: 1,
			reference: JSON.stringify({ title: "Centauro" }),
		},
		{
			partner_id: 284,
			source_id: 1,
			reference: JSON.stringify({ title: "Ciclic Seguro Viagem" }),
		},
		{
			partner_id: 285,
			source_id: 1,
			reference: JSON.stringify({ title: "Claro" }),
		},
		{
			partner_id: 286,
			source_id: 1,
			reference: JSON.stringify({ title: "D'Or Mais Saude" }),
		},
		{
			partner_id: 287,
			source_id: 1,
			reference: JSON.stringify({ title: "Dr Jones" }),
		},
		{
			partner_id: 288,
			source_id: 1,
			reference: JSON.stringify({ title: "Hering Outlet" }),
		},
		{
			partner_id: 289,
			source_id: 1,
			reference: JSON.stringify({ title: "Lacoste" }),
		},
		{
			partner_id: 290,
			source_id: 1,
			reference: JSON.stringify({ title: "Aramis" }),
		},
		{
			partner_id: 291,
			source_id: 1,
			reference: JSON.stringify({ title: "Max Titanium" }),
		},
		{
			partner_id: 292,
			source_id: 1,
			reference: JSON.stringify({ title: "MedSenior" }),
		},
		{
			partner_id: 293,
			source_id: 1,
			reference: JSON.stringify({ title: "O.U.i Paris" }),
		},
		{
			partner_id: 294,
			source_id: 1,
			reference: JSON.stringify({ title: "Probiotica" }),
		},
		{
			partner_id: 295,
			source_id: 1,
			reference: JSON.stringify({ title: "Seguro Residencial MAPFRE" }),
		},
		{
			partner_id: 296,
			source_id: 1,
			reference: JSON.stringify({ title: "Shopee" }),
		},
		{
			partner_id: 297,
			source_id: 1,
			reference: JSON.stringify({ title: "Vult" }),
		},
	]).onConflict([
		"partner_id",
		"source_id",
	]).merge();
}
