@token = {{$dotenv API_TOKEN}}
@baseURL = http://localhost:3366/v1
# @baseURL = https://api.consultapontos.com.br/v1

### Get all sources
GET {{baseURL}}/source?page=1&perPage=15
Authorization: Bearer {{token}}

### Get source information
GET {{baseURL}}/source/1
Authorization: Bearer {{token}}

### Get all partners
GET {{baseURL}}/partner
Authorization: Bearer {{token}}

### Get partner information
GET {{baseURL}}/partner/1
Authorization: Bearer {{token}}

### Get source parities
GET {{baseURL}}/parity/source/1
Authorization: Bearer {{token}}

### Get parity history
GET {{baseURL}}/parity/source/1/partner/1/history
Authorization: Bearer {{token}}

### Refresh data
POST {{baseURL}}/refresh
Authorization: Bearer {{token}}