@token = {{$dotenv API_TOKEN}}

### Get all sources
GET http://localhost:3366/source?page=1&perPage=15
Authorization: Bearer {{token}}

### Get all partners
GET http://localhost:3366/partner
Authorization: Bearer {{token}}

### Get source information
GET http://localhost:3366/source/1
Authorization: Bearer {{token}}

### Get source parities
GET http://localhost:3366/source/1/parity
Authorization: Bearer {{token}}

### Get parity history
GET http://localhost:3366/source/1/parity/1/history
Authorization: Bearer {{token}}